"""Deployment script generation — platform-agnostic vLLM + GPU monitor.

Generates a shell script per experiment that starts:
  1. vLLM server on port 8000
  2. gpu_monitor.py on port 8081 (nvidia-smi HTTP server)

Both run as background processes managed by a single script with proper
cleanup on exit (trap). The GPU monitor runs in a separate process and
does NOT interfere with inference — it only shells out to nvidia-smi
on demand when polled by the benchmarking client.
"""

from __future__ import annotations

from pathlib import Path

from .config import _project_root
from .schemas import ExperimentConfig, VLLMArgs

SCRIPTS_DIR_NAME = "scripts/experiments"
GPU_MONITOR_PORT = 8081

# Read gpu_monitor.py source at import time so it can be embedded in generated scripts.
_GPU_MONITOR_SRC = _project_root() / "scripts" / "gpu_monitor.py"
_GPU_MONITOR_CODE = _GPU_MONITOR_SRC.read_text()


def _scripts_dir() -> Path:
    d = _project_root() / SCRIPTS_DIR_NAME
    d.mkdir(parents=True, exist_ok=True)
    return d


def _build_vllm_command(args: VLLMArgs) -> list[str]:
    """Convert VLLMArgs to vllm serve CLI command."""
    cmd = [
        "vllm",
        "serve",
        args.model,
        "--revision",
        args.revision,
        "--served-model-name",
        args.model,
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--dtype",
        args.dtype,
        "--max-model-len",
        str(args.max_model_len),
        "--max-num-seqs",
        str(args.max_num_seqs),
        "--gpu-memory-utilization",
        str(args.gpu_memory_utilization),
    ]
    if args.enforce_eager:
        cmd.append("--enforce-eager")
    if args.enable_chunked_prefill:
        cmd.append("--enable-chunked-prefill")
    if args.enable_prefix_caching:
        cmd.append("--enable-prefix-caching")
    if args.speculative_config:
        cmd.extend(["--speculative-config", args.speculative_config])
    cmd.extend(args.extra_args)
    return cmd


def generate_script(experiment: ExperimentConfig) -> Path:
    """Generate a platform-agnostic shell script.

    The script starts both vLLM (:8000) and gpu_monitor (:8081) as background
    processes. On SIGINT/SIGTERM (Ctrl-C or kill), both are cleaned up.

    Usage on the GPU server:
        bash scripts/experiments/baseline.sh
    """
    cmd_parts = _build_vllm_command(experiment.vllm)
    vllm_cmd = " ".join(cmd_parts)

    script = f"""\
#!/usr/bin/env bash
# Auto-generated by how-fast for experiment: {experiment.name}
# {experiment.description}
#
# Starts:
#   vLLM              on port 8000
#   GPU monitor        on port {GPU_MONITOR_PORT}
#
# Usage:
#   bash {experiment.name}.sh
#
# From your laptop, set up SSH tunnels:
#   ssh -L 8000:localhost:8000 -L {GPU_MONITOR_PORT}:localhost:{GPU_MONITOR_PORT} user@gpu-server
#
set -euo pipefail

VLLM_PID=""
GPU_MON_PID=""

cleanup() {{
    echo ""
    echo "[launcher] shutting down..."
    [[ -n "$GPU_MON_PID" ]] && kill "$GPU_MON_PID" 2>/dev/null && echo "[launcher] gpu_monitor stopped"
    [[ -n "$VLLM_PID" ]] && kill "$VLLM_PID" 2>/dev/null && echo "[launcher] vLLM stopped"
    wait 2>/dev/null
    [[ -f "$GPU_MONITOR" ]] && rm -f "$GPU_MONITOR"
    echo "[launcher] done"
}}
trap cleanup EXIT INT TERM

echo "============================================================"
echo "  Experiment: {experiment.name}"
echo "  Model:      {experiment.vllm.model}"
echo "  GPU type:   {experiment.gpu_type}"
echo "  vLLM port:  8000"
echo "  GPU monitor: {GPU_MONITOR_PORT}"
echo "============================================================"

# ── Write embedded gpu_monitor to a temp file ──
GPU_MONITOR=$(mktemp /tmp/gpu_monitor_XXXXXX.py)
cat > "$GPU_MONITOR" << 'PYTHON_EOF'
{_GPU_MONITOR_CODE}PYTHON_EOF

# ── Start GPU monitor (lightweight, no deps) ──
echo "[launcher] starting gpu_monitor on :{GPU_MONITOR_PORT}..."
python3 "$GPU_MONITOR" --port {GPU_MONITOR_PORT} &
GPU_MON_PID=$!

# ── Start vLLM ──
echo "[launcher] starting vLLM on :8000..."
{vllm_cmd} &
VLLM_PID=$!

echo "[launcher] waiting for processes (Ctrl-C to stop)..."
wait
"""

    path = _scripts_dir() / f"{experiment.name}.sh"
    path.write_text(script)
    path.chmod(0o755)
    return path


def generate_all(experiments: list[ExperimentConfig]) -> list[Path]:
    """Generate shell scripts for all experiments."""
    paths: list[Path] = []
    for exp in experiments:
        path = generate_script(exp)
        paths.append(path)
    return paths
